travis:
  secure:
    BINSTAR_TOKEN: imzyFO6p2XgkMcfgQ9sNyV7wOvekcvtj2PvM3pG2nxSnByQZJ+D8dyw3Eeto8yuDM2GM1SViW/zwBTOWXkYLTLDuPMgIUKAbj6es3ncDZkYEK8tYHv+C+Vrhl2iG5fINoDeGtxh6nsnwDDLJutb6/FaYP28eRHCqyBDl+n5CHQ56nZGlvR3Mpe8s+JqWowbILkOQSJyG0tgo8pgFSGzLG2v0r7r/bVlatZyQnW8IB/6UXTIpF5EnoNdD95rQadJenEw9jZ93K2Ym4m7ksB6OIDEDLu3pjQEish1/lsZiuy+saJ3ACK5FHiHHMII4sdx73HVx/tHA9rSpKPgdngdkkjXcv2obwpGSqh1IWuxGQv55OXA+K1uTFANFr6YqsGJRFpfat07+Hb7TUWXZMRdLjmugHr9F4jE8hpcDawgDo1GMp2vcht2oMc/DjmONTGibgIN7OiurGd/qUIV08nFXAIpUU/luZ9CSBYCxhpinwKjZUWqk8APs4XrhNTBpqJ7VXAD2oUEpJ7ecAM9XGT+4nDZ8dJc3DJcPdqg/MKDRY7SLn20Bz2IwNBMVFokw8lKNk1IIkg5ouWwfLMbUkAmHGOTTxCd7ipELptDfwuDctNjKylHcfZln/Wku8MhCIErs8PTLi4PBKHzXCW7FFBhnYy/qPRdIKxJmAyKjX2fDPGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
