appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 5uB7vXA6r5tH9wwqqUEpCHsMRytvrTqqb9RTEkwfkhaX6rfu6B44kk17YkJyAVxJV5ug/Mv8odfJupaL1/TDE40HMb4Zvc3DeA3ZR5SHpj+D0JfV9bNMCm+pkeyleSv7K1/vfkZU4czIijGRI8QVztQMRusKuzeeLV6QnBkwulQkt90SIw9NTg+L1UPATZwAj3xe0BW3yw875k37d3ITuY8FTxZ2Ot13u9FPtXG3q5mICowyeAMuzKhzgwdHKmSWTxV13QsmknDJnJqOB/fdWAeFCk8xL6BvspuDk44SLN2FgauswiHZpZq0qb4q1HxnNu8JlYdsGGNtPjM0R3uq7JgLr7X7m3/KN2Gv2qR5vQEs7i8QvI3md6s/vIZLB/q0laXrSie25olNCBL3EJhKEi52bWdwUsiNoycd//4bNquQEwfdWYxXNXcvwZK66QtFkZw8Eas/QJmSFeVvR26Acpf8GRY2BRr8vS5Cra0zK2uClcN/XiGfCtE9/5cceOeNnM9tyB9eZ0gVeLWti2VeyMCfLFhyhtLLcWSYXh6WTxU/hord0ui+hkP/QVFFrydQIpM47XFm/TB4YfiFnXm5T+03uwd92Hh8wQNCQV5p5ncMhqcLeITRUJmVknKaZYAuuzpG9P3+vJk4cYJAgyTdPQ1ErZLMIwh17qrIeOjLp7g=
conda_forge_output_validation: true
